### **1. Introduction to PyTorch, a Deep Learning Library**

In [76]:
import torch
import numpy as np

**Tensor from a List**

In [77]:
lst = [[1,2,3], [4,5,6] , [7,8,9]]
tensor = torch.tensor(lst)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


**Tensor from a NumPy Array**

In [78]:
array = [[1,2,3], [4,5,6] ]
np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)
print(np_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


**Tensor Attributes**

In [79]:
print(tensor.shape)
print(np_tensor.shape)

torch.Size([3, 3])
torch.Size([2, 3])


In [80]:
print(tensor.dtype)
print(np_tensor.dtype)

torch.int64
torch.int32


In [81]:
tensor.device

device(type='cpu')

**Tensor operations**

In [82]:
# Addition
a = torch.tensor([[1,1],[2,2]])
b = torch.tensor([[2,2],[3,3]])
print(a+b)

tensor([[3, 3],
        [5, 5]])


In [83]:
# Multiplication
a = torch.tensor([[1,1],[2,2]])
b = torch.tensor([[2,2],[3,3]])
print(a*b)

tensor([[2, 2],
        [6, 6]])


##### **First neural Network**

In [84]:
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 4),  #1st Linear Layer
                      nn.Linear(4, 1),  #2nd Linear Layer
                     )

output = model(input_tensor)
print(output)

tensor([[-0.3380]], grad_fn=<AddmmBackward0>)


In [85]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 4),  #1st Linear Layer
                      nn.Linear(4, 1),  #2nd Linear Layer
                      nn.Sigmoid()
                     )

output = model(input_tensor)
print(output)

tensor([[0.9569]], grad_fn=<SigmoidBackward0>)


**Create a sigmoid function and apply it on input_tensor**

In [86]:
input_tensor = torch.tensor([[0.8]])
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


**Create a softmax function and apply it on input_tensor**

In [87]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])
softmax = nn.Softmax(dim=-1)
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


### **2. Training Our First Neural Network with PyTorch**

**Recap**

**(i) Binary Classification (foward pass)**

In [88]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)


tensor([[0.6220]], grad_fn=<SigmoidBackward0>)


**(ii) Multiclass Classification (foward pass)**

In [89]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

n_classes = 3 
# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6,n_classes), 
  nn.Softmax(dim = -1)
)

output = model(input_tensor)
print(output)

tensor([[0.1522, 0.0838, 0.7640]], grad_fn=<SoftmaxBackward0>)


**(iii) Regression (foward pass)**

In [90]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 1),  
)

output = model(input_tensor)
print(output)

tensor([[-0.4365]], grad_fn=<AddmmBackward0>)


##### **Using loss functions to assess model predictions**

### **3. Neural Network Architecture and Hyperparameters**

### **4. Evaluating and Improving Models**