#### **1. Introduction to PyTorch, a Deep Learning Library**

In [20]:
import torch
import numpy as np

**Tensor from a List**

In [21]:
lst = [[1,2,3], [4,5,6] , [7,8,9]]
tensor = torch.tensor(lst)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


**Tensor from a NumPy Array**

In [22]:
array = [[1,2,3], [4,5,6] ]
np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)
print(np_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


**Tensor Attributes**

In [23]:
print(tensor.shape)
print(np_tensor.shape)

torch.Size([3, 3])
torch.Size([2, 3])


In [24]:
print(tensor.dtype)
print(np_tensor.dtype)

torch.int64
torch.int32


In [25]:
tensor.device

device(type='cpu')

**Tensor operations**

In [26]:
# Addition
a = torch.tensor([[1,1],[2,2]])
b = torch.tensor([[2,2],[3,3]])
print(a+b)

tensor([[3, 3],
        [5, 5]])


In [27]:
# Multiplication
a = torch.tensor([[1,1],[2,2]])
b = torch.tensor([[2,2],[3,3]])
print(a*b)

tensor([[2, 2],
        [6, 6]])


##### **First neural Network**

In [28]:
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 4),
                      nn.Linear(4, 1),
                     )

output = model(input_tensor)
print(output)

tensor([[1.4833]], grad_fn=<AddmmBackward0>)


#### **2. Training Our First Neural Network with PyTorch**

#### **3. Neural Network Architecture and Hyperparameters**

#### **4. Evaluating and Improving Models**